name: pulsar-playground

channels:
  - conda-forge
  - defaults

dependencies:
  - appmode
  - ipywidgets
  - defaults::numpy           # Force to use 'defaults' NumPy which is compiled against MKL.
  - seaborn
  - scikit-learn=0.18.2
  - imbalanced-learn
  - xgboost
  - tensorflow
  - keras
  - sphinx
  - pip
  - pip:
    - sphinx_rtd_theme
